src/app/components/DirectoryStatus.tsx, src/app/creators/[username]/MembershipStatus.tsx, src/app/creators/[username]/page.tsx, src/app/features/directory/actions.ts, src/app/frames/hello/components/ContractGallery.tsx
- **fix up some images**
- **cleanup edit form**
=> profile show cleanup

src/app/creators/[username]/Gives.tsx, src/app/creators/[username]/page.tsx, src/app/features/directory/actions.ts, src/app/features/directory/types.ts, src/components/Countdown.tsx, src/lib/apollo-client.ts
=> add gives to profile

src/app/creators/[username]/basenames.tsx, src/app/creators/[username]/edit/EditBasenameProfile.tsx, src/app/hooks/useBasenameResolver.ts
- **add gives to profile**
- **Add avail for hire**
=> add avail for hire

src/app/creators/[username]/page.tsx, src/components/WhoAmI.tsx
=> use basename in header

src/app/creators/ogimage/route.tsx
=> random avatars for directory og front door

src/app/creators/[username]/InfoCard.tsx, src/app/creators/[username]/edit/EditBasenameProfile.tsx
- **fix creative medium info card**
- **update-base-text**
=> update base text

src/app/components/ShareButton.tsx, src/app/creators/CreatorsList.tsx, src/app/creators/[username]/page.tsx, tailwind.config.ts
=> share link for directory and profile

src/app/components/ContractGallery.tsx, src/app/creators/[username]/Gives.tsx, src/app/creators/[username]/InfoCard.tsx, src/app/creators/[username]/page.tsx
=> styling infocard

src/components/FrameOrWalletConnection.tsx
remove the explicit check for window.ethereum, it breaks frames
=> fix wallet connection

src/app/creators/join/JoinClient.tsx
Enable debug mode for testing eligibility with:
// Ctrl/Cmd + Shift + D to toggle debug mode
=> add debug tools

src/app/creators/join/JoinClient.tsx, src/lib/getNFTContracts.ts, src/lib/getOpenseaNFTContracts.ts, src/lib/getZapperNFTContracts.ts
- **add debug tools**
- **fix chain nft filtering**
=> fix get nft

src/app/creators/CreatorsList.tsx, src/app/features/directory/actions.ts, src/lib/getNFTContracts.ts, src/lib/getOpenseaNFTContracts.ts, src/lib/getZapperNFTContracts.ts
- **redirect on join page if already member**
- **remove no image nfts**
=> exlcude no image nfts

src/app/components/ContractGallery.tsx, src/app/creators/CreatorsList.tsx
=> add new gallery view

src/app/components/ContractGallery.tsx, src/app/creators/CreatorsList.tsx, src/app/creators/[username]/ogimage/route.tsx, src/app/creators/[username]/page.tsx, src/app/features/directory/actions.ts, src/app/features/directory/types.ts, src/components/WhoAmI.tsx
- **add new gallery view**
- **rename openseaData to nftData**
=> rename opensea nftdata

src/app/creators/join/JoinClient.tsx
=> add dir link to join page

src/app/components/ContractGallery.tsx, src/app/creators/[username]/Gives.tsx, src/app/creators/[username]/InfoCard.tsx, src/app/creators/[username]/RefreshButton.tsx, src/app/creators/[username]/page.tsx, src/app/features/directory/actions.ts, src/app/features/directory/types.ts, src/app/utils/address.ts, src/components/WhoAmI.tsx, src/lib/constants.ts
=> Intent cast to give

src/app/creators/CreatorsList.tsx, src/app/creators/[username]/basenames.tsx, src/app/creators/components/CreatorsSearch.tsx, src/app/features/directory/castCreateGive.ts
=> Click give skills to nav to dir

src/app/features/directory/actions.ts
takes load time from 20s to 10s for full getCreatorsfromAPI call
=> hydrate creators in batches

src/app/creators/CreatorsList.tsx, src/app/creators/[username]/loading.tsx
Show a loading state for the transitions
=> Create loadng transition

src/app/components/ShareButton.tsx, src/app/creators/CreatorsList.tsx, src/app/creators/components/CreatorsSearch.tsx
=> Sort dir bubs

package.json, pnpm-lock.yaml, src/app/components/FarcasterFollowButton.tsx, src/app/features/directory/neynar.ts
=> Farcaster Follow Button - Check following, Conditional styling
